Pw 3
alexxaski/An-introduction-to-OOP.-Encapsulation pull request #2
Opened 2024-11-19 19:32 UTC by alexxaski

2024-11-20 17:51 UTC, AleksandrZhukovJava requested changes

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/FixPriceProduct.java
> +   public FixPriceProduct(String productName,int price ) {
Зачем передавать цену если она фиксированная?

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/product/Product.java
> +   // final   int price;
идея добавить сюда была верной, так и нужно сделать, любой продукт имеет цену

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/product/Product.java
> +    public abstract int getPrice();
Тогда это можно будет реализовать по дефолту

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/DiscountedProduct.java
> +        return basePrice - (basePrice * discountPercentage / 100);
Если в родителе будет приниматься в конструктор цена, это можно будет передать в super

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/DiscountedProduct.java
> +    }
тоже в родителя

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/FixPriceProduct.java
> +    private static final int FIXED_PRICE = 50;
это можно будет передать в родителя по дефолту super(productName, 50)

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/basket/ProductBasket.java
> +        System.out.println(productName + ": " + price);
Это дублирует toString просто распечатай Product

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/DiscountedProduct.java
> +    }
тоже можно сделать полем родителя

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/basket/ProductBasket.java
> +    public int calculateBasketCost() {
Допустимо 
public int calculateBasketCost() {
        int sum = 0;
        for (int i = 0; i < counter; i++) {
            sum += basket[i].getPrice();
        }
        return sum;
    }

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/basket/ProductBasket.java
> +            } else if (counter == 0) {
Это надо вынести в начало метода

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/basket/ProductBasket.java
> +    public boolean isThereProduct(String productName) {
лучше containsProduct

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/basket/ProductBasket.java
> +        Arrays.fill(basket, null);
Можно basket = new Product[basket.length] что бы без итераций

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/basket/ProductBasket.java
> +        if (counter == 0) {
это в самое начало

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/basket/ProductBasket.java
> +        System.out.println("Специальных товаров: " + specialCount);
Это надо передвинуть ниже под условие, в условии добавить return

2024-11-20 17:51 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/basket/ProductBasket.java
> +        for (Product product : basket) {
зачем 2 цикла, можно всё сделать в 1

2024-11-22 06:55 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/product/Product.java
> +   // final   int price;
UPD: Оставил комментарий на тему этого в обратной связи по ДЗ, цену можно оставить в наследниках

2024-11-22 09:22 UTC, alexxaski commented on src/org/skypro/skyshop/basket/ProductBasket.java
> +        if (counter == 0) {
исправил вроде все

2024-11-22 12:22 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/DiscountedProduct.java
>          this.basePrice = basePrice;
Если бы не было задания на удаление из оснвного класса то и эту строчку можно было бы убрать и поле цены отсюда точно, мы бы его получали из родителя, но по ТЗ все корректно

2024-11-27 08:04 UTC, merged